# Generated by Django 3.1.4 on 2022-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_logitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='picture',
        ),
        migrations.AlterField(
            model_name='logitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='utime',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
    ]
