# Generated by Django 3.1.4 on 2022-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20220612_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='new_club',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (7, '7')], default=25, verbose_name='新社團'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='old_club',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (7, '7')], default=25, verbose_name='舊社團'),
        ),
    ]
