# Generated by Django 3.1.4 on 2022-06-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20220614_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='logitem',
            name='reporter',
        ),
        migrations.AlterField(
            model_name='logitem',
            name='description',
            field=models.TextField(verbose_name='轉社原因'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='subject',
            field=models.CharField(max_length=4, verbose_name='申請人員'),
        ),
    ]
