# Generated by Django 3.1.4 on 2022-06-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20220614_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='申請人員'),
        ),
    ]
