# Generated by Django 3.1.4 on 2022-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20220614_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='new_club',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '1社'), (2, '2社'), (3, '3社'), (4, '4社'), (5, '5社'), (7, '6社')], default=25, verbose_name='新社團'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='old_club',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '1社'), (2, '2社'), (3, '3社'), (4, '4社'), (5, '5社'), (7, '6社')], default=25, verbose_name='舊社團'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='status',
            field=models.IntegerField(choices=[(0, '待處理'), (1, '處理中'), (2, '已結案'), (3, '社長認證')], default=0, verbose_name='處理進度'),
        ),
    ]
