# Generated by Django 3.1.4 on 2022-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20220619_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='status',
            field=models.IntegerField(choices=[(0, '未認證'), (1, '未通過'), (2, '舊社長認證'), (3, '新社長認證'), (4, '新老師認證'), (5, '舊老師認證'), (6, '組長認證')], default=0, verbose_name='處理進度'),
        ),
    ]
